### PR TITLE
Renamed transaction param for rpc simulateTransactions

### PR DESCRIPTION
**Pull request by ivpavici**
## Usage related changes

- Renamed `transaction` param to `transactions` for rpc simulateTransactions, because this name will change in the rpc spec

## Development related changes

N/A

## Checklist:

- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/lint.sh`
- [x] Performed code self-review
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Documented the changes
- [ ] Linked the issues which this PR resolves
- [x] Updated the tests
- [x] All tests are passing - `./scripts/test.sh`

### CODE REVIEW

**Comment by mikiw** [comment]
Looks legit to me but let's wait for an updated version of the specification before merging to master.

**Review by mikiw — APPROVED** [review]
Looks legit to me but let's wait for an updated version of the specification before merging to master.

**Comment by ivpavici** [comment]
https://github.com/starkware-libs/starknet-specs/pull/103/files

> Looks legit to me but let's wait for an updated version of the specification before merging to master.

Made a PR on specs:
https://github.com/starkware-libs/starknet-specs/pull/103/files

**Review by FabijanC — APPROVED** [review]
As discussed, we should merge this ASAP because others have already implemented this change (despite not being a part of an official specification).

**Pull request merged**
