### PR TITLE
Update felt schema to be less strict

### LINKED ISSUE #401: RPC schema felt validation
**Describe the bug (observed vs expected behavior)**

For the RPC schema validation of the latest `devnet` version the regular expression used for validating `felt` fields seems to be too strict. It necessitates that the corresponding values conform to the `0x0{digits}` format, while for the earlier versions and for `testnet` the `0x{digits}` format is accepted.

For the payload:
```
{
    "jsonrpc": "2.0",
    "method": "starknet_getClass",
    "params": {
        "block_id": "latest",
        "class_hash": "0x25ec026985a3bf9d0cc1fe17326b245dfdc3ff89b8fde106542a3ea56c5a918"
    },
    "id": 0
}
```
- `testnet` replies with a successful response
- `devnet 0.4.4` replies with the expected `UNDECLARED_CLASS` error
- `devnet 0.4.5` replies with the unexpected `"Got invalid value for parameter: \"'0x25ec026985a3bf9d0cc1fe17326b245dfdc3ff89b8fde106542a3ea56c5a918' does not match '^0x0[a-fA-F0-9]{1,63}$'\""` error message

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**Devnet version**

- I am using Devnet version: 0.4.5
- [x] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: 0.4.4

### PR DESCRIPTION
**Pull request by fracek**
## Usage related changes

Update the schema used to validate felts to the most recent version
included in starknet-specs.
This schema is less strict, and allows felts that are not zero-padded.

Fix #401

## Development related changes

No changes

## Checklist:

- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/lint.sh`
- [x] Performed code self-review
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Documented the changes
- [x] Linked the issues which this PR resolves
- [ ] Updated the tests
- [ ] All tests are passing - `./scripts/test.sh`

### CODE REVIEW

**Comment by penovicp** [comment]
I can see the regex used was based on the [recent change in spec](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L1030), however, it looks like it might be missing some parentheses. `^0x(0|[a-fA-F1-9]{1}[a-fA-F0-9]{0,62})` checks for `0x followed by 0 or the rest`, the intent was probably for it to be `^0x(0|[a-fA-F1-9]{1})([a-fA-F0-9]{0,62})$` so it checks for `0x followed by 0|[a-fA-F1-9]{1} followed by [a-fA-F0-9]{0,62}`.

I'm unsure if the regex should maybe be `^0x0?[a-fA-F0-9]{1,63}$` so the leading zero is only optional and doesn't affect the count of significant digits.

**Comment by ClementWalter** [comment]
@penovicp see my correponding PR https://github.com/Shard-Labs/starknet-devnet/pull/413 with the `?` which seems to me the most easy and straighforward change

**Comment by FabijanC** [comment]
@ClementWalter @penovicp
Doesn't `^0x0?[a-fA-F0-9]{1,63}$` then allow 64 digits after `0x`? Should that be considered legal?

**Comment by FabijanC** [comment]
Personally I'm leaning towards Clement's #413

**Comment by fracek** [comment]
Agree! Let's keep it simple!

**Comment by FabijanC** [comment]
As pointed out [here](https://github.com/Shard-Labs/starknet-devnet/issues/401#issuecomment-1448121152), we should reopen this PR and close #413.

@fracek Would you know how to resolve the issue arising with this PR?

**Comment by fracek** [comment]
The error originates when validating the response of calling `starknet_getBlockWithTxs` on the genesis block. I haven't investigated too much why it happens.

**Comment by FabijanC** [comment]
@mikiw Can you take a look

**Comment by mikiw** [comment]
> The error originates when validating the response of calling `starknet_getBlockWithTxs` on the genesis block. I haven't investigated too much why it happens.

I'll take a look now.

**Comment by mikiw** [comment]
```
============================================ short test summary info =============================================
FAILED test/rpc/test_rpc_blocks.py::test_get_block_with_tx_hashes[hash] - KeyError: 'result'
FAILED test/rpc/test_rpc_blocks.py::test_get_block_with_tx_hashes[number] - KeyError: 'result'
FAILED test/rpc/test_rpc_blocks.py::test_get_block_with_tx_hashes[tag] - KeyError: 'result'
FAILED test/rpc/test_rpc_blocks.py::test_get_block_with_tx_hashes[tag_pending] - KeyError: 'result'
FAILED test/rpc/test_rpc_blocks.py::test_get_block_with_tx_hashes_raises_on_incorrect_block_id[block_id1] - assert {'code': -326...]{0,62})$\'"'} == {'code': 24, ...ck not found'}
FAILED test/rpc/test_rpc_blocks.py::test_get_block_with_txs[hash] - KeyError: 'result'
FAILED test/rpc/test_rpc_blocks.py::test_get_block_with_txs[number] - KeyError: 'result'
FAILED test/rpc/test_rpc_blocks.py::test_get_block_with_txs[tag] - KeyError: 'result'
FAILED test/rpc/test_rpc_blocks.py::test_get_block_with_txs[tag_pending] - KeyError: 'result'
FAILED test/rpc/test_rpc_blocks.py::test_get_block_with_txs_raises_on_incorrect_block_id[block_id1] - assert {'code': -326...]{0,62})$\'"'} == {'code': 24, ...ck not found'}
FAILED test/rpc/test_rpc_blocks.py::test_get_block_transaction_count[hash] - KeyError: 'result'
FAILED test/rpc/test_rpc_blocks.py::test_get_block_transaction_count_raises_on_incorrect_block_id[block_id1] - assert {'code': -326...]{0,62})$\'"'} == {'code': 24, ...ck not found'}
==================================== 12 failed, 7 passed in 136.81s (0:02:16) ====================================
```

I got this test results.

**Comment by mikiw** [comment]
In tests we use dummy data like `0x1` I advise to disable validation in those tests to avoid many changes from `0x1` to `0x000000000000000000000000000000000000000000000000000000000000001`

**Comment by mikiw** [comment]
I made a 2fecdd96304bd3a90b2f2fe28a2a2c6f7fa3e478 commit with some test fixes

**Comment by mikiw** [comment]
Actually, I reverted that, seems that fix can be made only by modifying the rpc_felt wrapper.

**Comment by FabijanC** [comment]
Superseded by https://github.com/0xSpaceShard/starknet-devnet/pull/467

**Pull request closed without merging**
