### PR TITLE
feat: add TransactionStatus.REVERTED to status

### PR DESCRIPTION
**Pull request by kasteph**
## Usage related changes

- add `TransactionStatus.REVERTED` to status

## Checklist:

- [ ] Applied formatting - `./scripts/format.sh`
- [ ] No linter errors - `./scripts/lint.sh`
- [ ] Performed code self-review
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Documented the changes
- [ ] Linked the issues which this PR resolves
- [ ] Updated the tests
- [ ] All tests are passing - `./scripts/test.sh`

### CODE REVIEW

**Comment by FabijanC** [comment]
Can you give an example of an issue that this PR resolves?

**Comment by kasteph** [comment]
@FabijanC sure! There could be a case where a contract/account has a status of Reverted. However, because this doesn't exist in that dictionary, it raises a KeyError and thus the server ultimately returns an HTTP 500 to the client.

**Comment by FabijanC** [comment]
I thought that perhaps you would have a ready example, but I see your point

 In any case, this Devnet supports only JSON-RPC specification 0.3.0 (the latest stable version is 0.4.0 and there is 0.5.0 incoming; [link to spec versions](https://github.com/starkware-libs/starknet-specs/releases)). In that sense, 0.3.0 does not yet mention tx reversion, so this status was not added.

If your PR does not in any way break the existing functionality, it could be merged, but I'd wait until Monday since it's the end of the work day (and week) in my time zone.

Devnet has mostly been rewritten in Rust, with some features still pending. You can check out the [devnet-rs repo](https://github.com/0xSpaceShard/starknet-devnet-rs). It currently supports JSON-RPC v0.4.0, with the trace API (e.g. simulateTransactions) being added at the time of writing this.

**Comment by FabijanC** [comment]
Let me know if this is a high priority for you.

**Comment by FabijanC** [comment]
@kasteph Then I guess it's not a high priority.

**Comment by kasteph** [comment]
Hi @FabijanC, yes, it's not a priority. I was able to find a workaround. I'll close this issue and start looking at the Rust implementation.

**Pull request closed without merging**
